/**
 * Created by player on 2017/12/12.
 */

define(function () {
  var areaCountData = {
    "code":"200",
    "data":[
      {
        "name":"海淀区",
        "value":395
      }
    ],
    "desc":"请求处理成功！",
    "result":"success"
  };
  var schoolRankingData={
    "code":"200",
    "data":{
      "dataList":[
        {
          "name":"明博第一小学",
          "value":192
        },
        {
          "name":"明博中学",
          "value":81
        },
        {
          "name":"服务中心校",
          "value":61
        },
        {
          "name":"庆丰小学",
          "value":14
        },
        {
          "name":"演示学校",
          "value":14
        },
        {
          "name":"北京市海淀教育局",
          "value":12
        },
        {
          "name":"明博服务实验校",
          "value":12
        },
        {
          "name":"明博小学",
          "value":6
        },
        {
          "name":"OA学校1",
          "value":3
        },
        {
          "name":"育才小学",
          "value":0
        }
      ],
      "pageCount":2,
      "pageNo":1,
      "pageSize":10,
      "totalSize":13
    },
    "desc":"请求处理成功！",
    "result":"success"
  };

  var areaDistribute = {
    "code":"200",
    "data":[
      {
        "name":"测试学校",
        "value":0
      },
      {
        "name":"北京市海淀教育局",
        "value":12
      },
      {
        "name":"服务中心校",
        "value":61
      },
      {
        "name":"明博第一小学",
        "value":192
      },
      {
        "name":"明博演示实验校",
        "value":0
      },
      {
        "name":"OA学校1",
        "value":3
      },
      {
        "name":"庆丰小学",
        "value":14
      },
      {
        "name":"育才小学",
        "value":0
      },
      {
        "name":"演示学校",
        "value":14
      },
      {
        "name":"明博服务实验校",
        "value":12
      },
      {
        "name":"明博中学",
        "value":81
      },
      {
        "name":"明博小学",
        "value":6
      },
      {
        "name":"明博高中",
        "value":0
      }
    ],
    "desc":"请求处理成功！",
    "result":"success"
  };
  var areaUsedData = {
    "code":"200",
    "data":{
      "total":0,
      "school":{
        "dataList":[
          {
            "name":"明博演示实验校",
            "value":0
          },
          {
            "name":"北京市海淀教育局",
            "value":0
          },
          {
            "name":"明博高中",
            "value":0
          },
          {
            "name":"OA学校1",
            "value":0
          },
          {
            "name":"测试学校",
            "value":0
          },
          {
            "name":"育才小学",
            "value":0
          },
          {
            "name":"明博服务实验校",
            "value":0
          },
          {
            "name":"演示学校",
            "value":0
          },
          {
            "name":"明博小学",
            "value":0
          },
          {
            "name":"明博第一小学",
            "value":0
          }
        ],
        "pageCount":2,
        "pageNo":1,
        "pageSize":10,
        "totalSize":13
      }
    },
    "desc":"请求处理成功！",
    "result":"success"
  };

  return {
    'areaCountData' : areaCountData,
    'schoolRankingData' : schoolRankingData,
    'areaDistribute' : areaDistribute,
    'areaUsedData' : areaUsedData
  };
});